/**
 * Multi-format Data Export Utility (CSV, Excel, PDF)
 */

// Format headers and objects into CSV format
export const exportToCSV = (data, filename = 'export.csv') => {
  if (!data || !data.length) return;

  const headers = Object.keys(data[0]);
  const csvRows = [];

  // Header line
  csvRows.push(headers.join(','));

  // Data lines
  data.forEach((row) => {
    const values = headers.map((header) => {
      let val = row[header] === null || row[header] === undefined ? '' : row[header];
      if (typeof val === 'object') val = JSON.stringify(val);
      const escaped = ('' + val).replace(/"/g, '""');
      return `"${escaped}"`;
    });
    csvRows.push(values.join(','));
  });

  const blob = new Blob([csvRows.join('\n')], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

// Export to Excel format (.csv with UTF-8 BOM for MS Excel compatibility)
export const exportToExcel = (data, filename = 'export.xlsx') => {
  if (!data || !data.length) return;

  const headers = Object.keys(data[0]);
  const csvRows = [];

  csvRows.push(headers.join('\t')); // Tab-delimited for Excel

  data.forEach((row) => {
    const values = headers.map((header) => {
      let val = row[header] === null || row[header] === undefined ? '' : row[header];
      if (typeof val === 'object') val = JSON.stringify(val);
      return ('' + val).replace(/\t/g, ' ');
    });
    csvRows.push(values.join('\t'));
  });

  // UTF-8 BOM prefix \uFEFF ensures Excel renders characters properly
  const blob = new Blob(['\uFEFF' + csvRows.join('\n')], { type: 'application/vnd.ms-excel;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

// Export to PDF format via clean printable HTML table overlay window
export const exportToPDF = (title, headers, dataRows, filename = 'export.pdf') => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const tableHeaders = headers.map((h) => `<th style="border: 1px solid #cbd5e1; padding: 10px; background-color: #0f172a; color: #ffffff;">${h}</th>`).join('');
  const tableBody = dataRows
    .map(
      (row) =>
        `<tr style="border: 1px solid #e2e8f0;">${row.map((val) => `<td style="border: 1px solid #e2e8f0; padding: 8px;">${val}</td>`).join('')}</tr>`
    )
    .join('');

  const htmlContent = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 20px; color: #1e293b; }
          h1 { color: #0f172a; font-size: 24px; margin-bottom: 8px; }
          p { color: #64748b; font-size: 14px; margin-bottom: 20px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 13px; }
          .footer { margin-top: 30px; font-size: 12px; color: #94a3b8; text-align: center; }
        </style>
      </head>
      <body>
        <h1>${title}</h1>
        <p>Exported on ${new Date().toLocaleString()} | AI Resume Analyzer Admin Portal</p>
        <table>
          <thead>
            <tr>${tableHeaders}</tr>
          </thead>
          <tbody>
            ${tableBody}
          </tbody>
        </table>
        <div class="footer">Confidential Admin Report - Generated by AI Resume Analyzer</div>
        <script>
          window.onload = function() {
            window.print();
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(htmlContent);
  printWindow.document.close();
};
